# Generated by Django 3.2.20 on 2023-09-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='device_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='customer_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
