# Generated by Django 3.2.20 on 2023-09-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_certificaterequest_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='certificate_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='certificate_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
