# Generated by Django 3.2.20 on 2023-09-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20230925_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='customer_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
