# Generated by Django 3.2.20 on 2023-09-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_certificaterequest_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.CharField(max_length=255)),
                ('person_name', models.CharField(max_length=255, unique=True)),
                ('project_type', models.CharField(max_length=255)),
                ('project_scope', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=10)),
            ],
        ),
    ]
