# Generated by Django 3.2.20 on 2023-09-28 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_personcertificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personcertificate',
            old_name='project_type',
            new_name='project_name',
        ),
    ]
