# Generated by Django 3.2.20 on 2023-10-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_project_type_personcertificate_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='site_id',
            field=models.CharField(max_length=100),
        ),
    ]
